### ISSUE TITLE
tracking ticket for releasing 1.1.0

### ISSUE THREAD

**Issue by slingamn** [oragono/oragono#539]
- [x] The fix for #518 is in #525, which in its current form implements `draft/resume-0.5` as described here: https://github.com/DanielOaks/ircv3-specifications/pull/2 . So we should make a decision on that specification, then merge either #525 or an update of it that corresponds to the approved `draft/resume-0.5`.
- [x] After that, there's #546, which fixes #536
- [x] Orthogonally, we can merge #538 and then get in touch with the person who requested the feature about how to get them an rc build
- [x] We need changelog, manual, and readme updates for the rc (WIP on this is in the published `changelog` branch)
- [x] We should merge PRs for the two new caps: https://github.com/oragono/oragono-site/pull/4 and https://github.com/oragono/oragono-site/pull/5
- [ ] Next step is to build and release the rc and contact the relevant people
- [ ] Let's spend a week or two taking bug reports
- [ ] Let's also see if we can get more translations in for the strings as they appear in the rc
- [ ] Release!

**Comment by slingamn** [comment]
Do we still need `README` as well as `README.md`? `README` seems to be getting stale, I propose removing it.

**Comment by DanielOaks** [comment]
README is what's bundled with the binary package, README.md is the GitHub stuff. Good to have both because `README` tries to stay easily-readable without needing to be passed through a MarkDown parser/viewer first.

**Comment by slingamn** [comment]
I think we're on track for a final release next week:

- [ ] Merge #564 
- [ ] Merge #566 
- [ ] Run that on darwin for a day or so
- [ ] More complete credits, including translators
